BUFF_KEYWORDS = {
    # dota2.ru
    "к силе": "strength",
    "к ловкости": "agility",
    "к интеллекту": "intelligence",
    "ко всем атрибутам": "all_attributes",
    "к здоровью": "health",
    "к мане": "mana",
    "к максимальному запасу маны": "mana",
    "к восстановлению здоровья": "health_regen",
    "к пополнению здоровья": "health_replenish_amp",
    "к восстановлению маны": "mana_regen",
    "к скорости передвижения": "move_speed",
    "к скорости передвижения героям ближнего боя": "move_speed_melee",
    "к скорости передвижения героям дальнего боя": "move_speed_ranged",
    "к скорости атаки": "attack_speed",
    "к скорости применения заклинаний": "cast_speed",
    "к скорости снарядов": "projectile_speed",
    "к скорости снарядов атак": "projectile_speed",
    "к дальности атаки": "attack_range_ranged",
    "к дальности применения заклинаний": "cast_range",
    "к радиусу заклинаний": "spell_radius",
    "к вампиризму": "lifesteal",
    "к вампиризму от заклинаний против героев": "spell_lifesteal_heroes",
    "к вампиризму от заклинаний против крипов": "spell_lifesteal_creeps",
    "к усилению вампиризма": "spell_lifesteal_amp",
    "к урону": "damage",
    "к урону (ближний бой)": "damage_melee",
    "к урону (дальний бой)": "damage_ranged",
    "к урону от заклинаний": "spell_damage",
    "к усилению урона от заклинаний": "spell_damage_amp",
    "к усилению урона способностей": "ability_damage_amp",
    "к броне": "armor",
    "к сопротивлению магии": "magic_resist",
    "к сопротивлению замедлению": "slow_resist",
    "к сопротивлению замедлениям": "slow_resist",
    "к сопротивлению эффектам": "status_resist",
    "к уклонению": "evasion",
    "к уменьшению затрат и потерь маны": "mana_efficiency",
    "к усилению восстановления маны": "mana_regen_amp",
    "макс. здоровья в секунду": "max_health_per_sec",
    # fandom
    "strength": "strength",
    "agility": "agility",
    "intelligence": "intelligence",
    "health": "health",
    "mana": "mana",
    "health regeneration": "health_regen",
    "health regen amp": "health_replenish_amp",
    "mana regeneration": "mana_regen",
    "mana regen amp": "mana_regen_amp",
    "mana efficiency": "mana_efficiency",
    "move speed": "move_speed",
    "attack speed": "attack_speed",
    "projectile speed": "projectile_speed",
    "base attack speed": "attack_speed",
    "cast range": "cast_range",
    "aoe radius": "spell_radius",
    "attack range": "attack_range_ranged",
    "attack damage": "damage",
    "damage": "damage",
    "spell damage amp": "spell_damage_amp",
    "ability damage amp": "ability_damage_amp",
    "lifesteal amp": "spell_lifesteal_amp",
    "spell lifesteal amp": "spell_lifesteal_amp",
    "spell lifesteal (hero)": "spell_lifesteal_heroes",
    "spell lifesteal (creep)": "spell_lifesteal_creeps",
    "armor": "armor",
    "magic resistance": "magic_resist",
    "slow resistance": "slow_resist",
    "status resistance": "status_resist",
    "evasion": "evasion",
    "max hp health regen": "max_health_per_sec",
}


STATS_MAPPING = {
    # generic
    "cast range": "cast_range",
    "ability cast range": "cast_range",
    "ability cast distance": "cast_range",
    # --- Magic damage amplification ---
    "spell amp bonus": "spell_damage_amp",
    "spell damage amp": "spell_damage_amp",
    "bonus magical damage": "bonus_magical_damage",
    "spell damage bonus": "spell_damage_bonus",
    "magic resistance reduction": "magic_resistance_reduction",
    "damage dealt as bonus damage": "dmg_dealt_as_bonus_dmg",
    "intelligence as damage per second": "int_as_dps",
    "damage per second": "damage_per_second",
    # --- Physical damage ---
    "armor reduction": "armor_reduction",
    "enemy armor reduction": "armor_reduction",
    "attack damage bonus": "attack_damage_bonus",
    "bonus attack damage": "attack_damage_bonus",
    "critical damage": "critical_damage",
    # --- Healing ---
    "heal amp": "heal_amp",
    "health restored": "health_restored",
    "health regen bonus": "health_regen_bonus",
    # --- Anti-healing ---
    "health restoration reduction": "heal_reduction",
    "enemy health restoration reduction": "enemy_heal_reduction",
}
